TheaterProject/TheatreCMS3/Areas/Blog/Controllers/BlogAuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS3.Models;

namespace TheatreCMS3.Areas.Blog.Models
{
    public class BlogAuthorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blog/BlogAuthors
        public ActionResult Index()
        {
            return View(db.BlogAuthors.ToList());
        }

        // GET: Blog/BlogAuthors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            if (blogAuthor == null)
            {
                return HttpNotFound();
            }
            return View(blogAuthor);
        }

        // GET: Blog/BlogAuthors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blog/BlogAuthors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BlogAuthorId,Name,Bio,JoinedDate,LeftDate")] BlogAuthor blogAuthor)
        {
            ModelState["LeftDate"].Errors.Clear();
            if (ModelState.IsValid)
            {
                db.BlogAuthors.Add(blogAuthor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogAuthor);
        }

        // GET: Blog/BlogAuthors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            if (blogAuthor == null)
            {
                return HttpNotFound();
            }
            return View(blogAuthor);
        }

        // POST: Blog/BlogAuthors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogAuthorId,Name,Bio,JoinedDate,LeftDate")] BlogAuthor blogAuthor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogAuthor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogAuthor);
        }

        // GET: Blog/BlogAuthors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            if (blogAuthor == null)
            {
                return HttpNotFound();
            }
            return View(blogAuthor);
        }

        // POST: Blog/BlogAuthors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            db.BlogAuthors.Remove(blogAuthor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TheaterProject/TheatreCMS3/Areas/Blog/Controllers/BlogPhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS3.Areas.Blog.Models;
using TheatreCMS3.Models;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Drawing;

namespace TheatreCMS3.Areas.Blog.Controllers
{
    public class BlogPhotosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

       
        


        // GET: Blog/BlogPhotos
        public ActionResult Index()
        {

            var blogPhotos = db.BlogPhotos.ToList();
           
            return View(blogPhotos);
        }

        // GET: Blog/BlogPhotos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            return View(blogPhoto);
        }

        // GET: Blog/BlogPhotos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blog/BlogPhotos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BlogPhoto blogPhoto, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null)
                {
                    blogPhoto.Photo = ConvertToBytes(ImageFile);
                }

                db.BlogPhotos.Add(blogPhoto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPhoto);
        }

        // GET: Blog/BlogPhotos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            return View(blogPhoto);
        }

        // POST: Blog/BlogPhotos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BlogPhoto blogPhoto, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null)
                {
                    blogPhoto.Photo = ConvertToBytes(ImageFile);
                }

                db.Entry(blogPhoto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPhoto);
        }

        // GET: Blog/BlogPhotos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            return View(blogPhoto);
        }

        // POST: Blog/BlogPhotos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPhoto blogPhoto = db.BlogPhotos.Find(id);
            db.BlogPhotos.Remove(blogPhoto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public byte[] ConvertToBytes(HttpPostedFileBase file)
        {
            byte[] bytes;
            using (BinaryReader br = new BinaryReader(file.InputStream))
            {
                bytes = br.ReadBytes(file.ContentLength);
            }
            return bytes;
        }



      
    }
}

TheaterProject/TheatreCMS3/Areas/Rent/Controllers/RentalHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS3.Areas.Rent.Models;
using TheatreCMS3.Models;

namespace TheatreCMS3.Areas.Rent.Controllers
{
    public class RentalHistoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rent/RentalHistories
        public ActionResult Index()
        {
            return View(db.RentalHistories.ToList());
        }

        // GET: Rent/RentalHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalHistory rentalHistory = db.RentalHistories.Find(id);
            if (rentalHistory == null)
            {
                return HttpNotFound();
            }
            return View(rentalHistory);
        }

        // GET: Rent/RentalHistories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rent/RentalHistories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RentalHistoryId,RentalDamaged,DamagesIncurred,Rental")] RentalHistory rentalHistory)
        {
            if (ModelState.IsValid)
            {
                db.RentalHistories.Add(rentalHistory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rentalHistory);
        }

        // GET: Rent/RentalHistories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalHistory rentalHistory = db.RentalHistories.Find(id);
            if (rentalHistory == null)
            {
                return HttpNotFound();
            }
            return View(rentalHistory);
        }

        // POST: Rent/RentalHistories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RentalHistoryId,RentalDamaged,DamagesIncurred,Rental")] RentalHistory rentalHistory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rentalHistory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rentalHistory);
        }

        // GET: Rent/RentalHistories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalHistory rentalHistory = db.RentalHistories.Find(id);
            if (rentalHistory == null)
            {
                return HttpNotFound();
            }
            return View(rentalHistory);
        }

        // POST: Rent/RentalHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RentalHistory rentalHistory = db.RentalHistories.Find(id);
            db.RentalHistories.Remove(rentalHistory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TheaterProject/TheatreCMS3/Views/Shared/Restricted.cshtml
@{
    ViewBag.Title = "Access Denied";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="text-danger m-3">Access Denied</h1>
    This page is only accessible to Theatre staff.
    <div>
        <img src="~/Content/images/restricted.png" alt="Access Denied" class="m-4" />
    </div>

    <div>
        <p>Please log in to authorized account.</p>
        <a href="@Url.Action("Login", "Account", new { area = "" })" class="btn btn-sm prod-btn w-25">Log In</a>
    </div>

</div>

TheaterProject/TheatreCMS3/Views/Shared/_DevNavbar.cshtml
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dev menu
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      Production Area
    @Html.ActionLink("Cast Members", "Index", "CastMembers", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Production Photos", "Index", "ProductionPhotos", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Productions", "Index", "Productions", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Calendar Events", "Index", "CalendarEvents", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
      Blog Area
    @Html.ActionLink("Blog Post", "Index", "BlogPosts", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Comments", "Index", "Comments", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Blog Author", "Index", "BlogAuthors", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Blog Photo", "Index", "BlogPhoto", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
      Rental area
    @Html.ActionLink("Rental Requests", "Index", "RentalRequests", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Rental", "Index", "Rentals", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Rental History", "Index", "RentalHistories", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    @Html.ActionLink("Rental Survey", "Index", "RentalSurvey", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
      Donation Area
    @Html.ActionLink("Donate","Index", "Donate", new {Area= "Donate" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
    
    
  </div>
</div>

TheaterProject/TheatreCMS3/Views/Shared/_Footer.cshtml
@using TheatreCMS3.Models

<footer>
  <div class="float-left footer-content">

    <div class="float-left footer-icons">
      <span>
        <i class="fab fa-facebook-f fa-2x"></i> &nbsp;
        <i class="fab fa-youtube fa-2x"></i> &nbsp;
        <i class="fab fa-twitter fa-2x"></i>
      </span>
    </div>
    <div class="footer-links">
      @Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "float-left" })
      @*<a class="float-left" href="#">About</a> added action link above *@
      @*<a class="float-right" href="3">Contact</a> added action link below *@
      @Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "float-right" })
    </div>
    <p class="footer-address">
      2110 SE 10th Ave
      <br />
      Portland, OR 97214
      <br />
      (503) 482-8655
    </p>
    <p class="footer-lcopyright">
      <i class="far fa-copyright"></i>
      &copy;
    </p>
  </div>

  <div class="float-right footer-rcontent">
    <span>
      <i class="fab fa-facebook-f fa-2x"></i> &nbsp;
      <i class="fab fa-youtube fa-2x"></i> &nbsp;
      <i class="fab fa-twitter fa-2x"></i>
    </span>
    <p class="footer-copyright">
      <i class="far fa-copyright"></i>
      2021
    </p>
  </div>

</footer>

TheaterProject/TheatreCMS3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @if (ViewContext.RouteData.DataTokens["area"] != null)
    {
        <link rel="stylesheet" href="~/Content/Areas/@(ViewContext.RouteData.DataTokens["area"]).css" />
    }
    <!--add google font for header section-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/634caf7d3f.js" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    @Html.Partial("_Navbar")
    @Html.Partial("_DevNavbar")
    <div class="container body-content">
        @RenderBody()

    </div>
    @Html.Partial("_Footer")

    @if (ViewContext.RouteData.DataTokens["area"] != null)
    {
        <script src="~/Scripts/Areas/@(ViewContext.RouteData.DataTokens["area"]).js"></script>
    }
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/Site.js")
</body>
</html>

TheaterProject/TheatreCMS3/Views/Shared/_Navbar.cshtml
@*<div class="navbar navbar-inverse navbar-fixed-top .navbar .navbar-expand{-sm|-md|-lg|-xl}">
        <div class="container">
            <div class="navbar-header">
                <a href="~/Home/Index"><img src="~/Content/images/TheatreLogo.png"/></a>

                <span><a href="#" class="icon-bar">Production</span>
                <span><a href="#" class="icon-bar">Rental</span>
                <span><a href="#" class="icon-bar">Blog</span>
            </div>
        </div>
    </div>*@



<nav class="navbar navbar-expand-lg navbar-light sticky-top nav-pills nav-fill ">
  <div class="container-fluid">
    <a href="~/Home/Index"><img src="~/Content/images/TheatreLogo.png" class="navbar-icon-red" /></a>
    <div class="navbar--hamburger">
      <!-- this holds the mobile nav in a hamburger menu -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span> <!-- actual humburger button -->
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav nav">
          <li class="nav-item navbar-hamburger--navitem">
            <a class="nav-link .navbar-hamburger--navlink" href="~/Home/Index">TheaterCMS</a>
          </li>
          <li class="nav nav-item dropdown navbar-hamburger--navitem">
            <a class="nav nav-link dropdown-toggle .navbar-hamburger--navlink" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Production
            </a>
            <div class="dropdown-menu dropdownbckgrndclr navbar-hamburger--dropdownmenu" aria-labelledby="navbarDropdownMenuLink">
              @Html.ActionLink("Cast Members", "Index", "CastMembers", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Production Photos", "Index", "ProductionPhotoes", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Productions", "Index", "Productions", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Calendar Events", "Index", "CalendarEvents", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
            </div>
          </li>
          <li class="nav-item navbar-hamburger--navitem">
            <a class="nav nav-link dropdown-toggle .navbar-hamburger--navlink" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Rental</a>
            <div class="dropdown-menu dropdownbckgrndclr" aria-labelledby="navbarDropdownMenuLink">
              @Html.ActionLink("Rental Requests", "Index", "RentalRequests", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Rental", "Index", "Rentals", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Rental Histories", "Index", "RentalHistories", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Rental Survey", "Index", "RentalSurvey", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
            </div>

          </li>
          <li class="nav-item dropdown navbar-hamburger--navitem">
            <a class="nav nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Blog
            </a>
            <div class="dropdown-menu dropdownbckgrndclr" aria-labelledby="navbarDropdownMenuLink">
              @Html.ActionLink("Blog Posts", "Index", "BlogPosts", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Comments", "Index", "Comments", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Blog Authors", "Index", "BlogAuthors", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
              @Html.ActionLink("Blog Photos", "Index", "BlogPhotos", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt navbar-hamburger--dropdownitem" })
            </div>
          </li>
        </ul>
      </div>
    </div> <!-- mobile nav end -->

    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="~/Home/Index">TheatreCMS</a>
      </li>
      <li class="nav nav-item dropdown ">
        <a class="nav nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Production
        </a>
        <div class="dropdown-menu dropdownbckgrndclr" aria-labelledby="navbarDropdownMenuLink">
            @Html.ActionLink("Cast Members", "Index", "CastMembers", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt" })
            @Html.ActionLink("Production Photos", "Index", "ProductionPhotoes", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt" })
            @Html.ActionLink("Productions", "Index", "Productions", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt" })
            @Html.ActionLink("Calendar Events", "Index", "CalendarEvents", new { Area = "Prod" }, new { @class = "dropdown-item dropdowntxt" })
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rental
        </a>
        <div class="dropdown-menu dropdownbckgrndclr" aria-labelledby="navbarDropdownMenuLink">
          @Html.ActionLink("Rental Requests", "Index", "RentalRequests", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt" })
          @Html.ActionLink("Rental", "Index", "Rentals", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt" })
          @Html.ActionLink("Rental Histories", "Index", "RentalHistories", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt" })
          @Html.ActionLink("Rental Survey", "Index", "RentalSurvey", new { Area = "Rent" }, new { @class = "dropdown-item dropdowntxt" })
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Blog
        </a>
        <div class="dropdown-menu dropdownbckgrndclr" aria-labelledby="navbarDropdownMenuLink">
          @Html.ActionLink("Blog Posts", "Index", "BlogPosts", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt" })
          @Html.ActionLink("Comments", "Index", "Comments", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt" })
          @Html.ActionLink("Blog Authors", "Index", "BlogAuthors", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt" })
          @Html.ActionLink("Blog Photos", "Index", "BlogPhotos", new { Area = "Blog" }, new { @class = "dropdown-item dropdowntxt" })
        </div>
      </li>
    </ul>
    @Html.Partial("_LoginPartial")
  </div>
</nav>